site_name: UEG Wiki
site_description: UEG Wiki
site_author: United Earth Wiki Team

repo_name: UE/UEG-Wiki
repo_url: https://github.com/UnitedEarths/UEG-WIKI
edit_uri: blob/master/docs/

theme:
  name: "material"
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    logo: ""

  features:
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Noto Sans
    code: Source Code Pro

markdown_extensions:
  # 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  - pymdownx.arithmatex:
      generic: true

  - admonition # 提示块
  - footnotes # 脚注
  - meta # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret # 下划线上标
  - pymdownx.tilde # 删除线下标
  - pymdownx.critic # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details # 提示块可折叠
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.mark # 文本高亮
  - pymdownx.smartsymbols # 符号转换
  - pymdownx.superfences # 代码嵌套在列表里
  - codehilite: # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc: # 锚点
      permalink: true
  #  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem: # 对加粗和斜体更好的检测
      smart_enable: all
  #  - pymdownx.emoji:  # 表情
  #      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist: # 复选框checklist
      custom_checkbox: true
extra:
  alternate:
    - link: /
      name: zh_cn - 简体中文
  copyright: CC BY-NC-SA 4.0
extra_javascript:
  - https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
  - static/js/custom.js
  - https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - static/css/custom.css

nav:
  - 天文学:
      - 太阳:
          - astronomy/sun/index.md
          - astronomy/sun/heliumflash.md
          - astronomy/sun/solarcrisis.md
          - astronomy/sun/solarstorm.md
          - astronomy/sun/gravityassist.md
      - 月球:
          - astronomy/moon/index.md
          - astronomy/moon/lunarsurface.md
          - astronomy/moon/gravitation.md
          - astronomy/moon/2058-event.md
      - 半人马座α星:
          - astronomy\alpha-centauri\stellar-migration.md
          - astronomy\alpha-centauri\alpha-centauri.md
          - astronomy\alpha-centauri\proxima-centauri.md
      - astronomy\asteroid-belt.md